version: "3"
services:
  php-fpm:
    container_name: php-fpm_container
    build: ./docker/php-fpm
    volumes:
      - ./app:/app
    restart: always

  nginx:
    container_name: nginx_container
    build: ./docker/nginx   
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: always
    links:
      - "php-fpm"